# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Diffusion": "00_hagerstrand.ipynb",
         "SimpleDiffusion": "00_hagerstrand.ipynb",
         "AdvancedDiffusion": "00_hagerstrand.ipynb"}

modules = ["hagerstrand.py"]

doc_url = "https://pages.github.CentroGeo.com./hager_py/hager_py/"

git_url = "https://github.CentroGeo.com/hager_py/hager_py/tree/main/"

def custom_doc_links(name): return None
